# Generated by Django 3.1.2 on 2021-03-20 08:15

from django.db import migrations
import utils.fields.sex


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=utils.fields.sex.SexField(choices=[('M', 'Man'), ('W', 'Woman'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
