# Generated by Django 3.1.2 on 2021-03-20 15:27

from django.conf import settings
from django.db import migrations, models
import utils.fields.status
import utils.fields.timestamp
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', utils.fields.status.StatusField(choices=[('A', 'Active'), ('W', 'Watting'), ('R', 'Remove')], default='W', max_length=1)),
                ('created_at', utils.fields.timestamp.TimeStamp(auto_now_add=True)),
                ('updated_at', utils.fields.timestamp.TimeStamp(auto_now=True)),
                ('friend', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
