# Generated by Django 3.1.2 on 2021-03-20 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='friend_creator', to='user.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='friend_friend', to='user.user'),
            preserve_default=False,
        ),
    ]
