# Generated by Django 3.1.2 on 2021-03-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20210320_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='sport',
        ),
        migrations.AddField(
            model_name='activity',
            name='sport',
            field=models.ManyToManyField(to='activity.Sport'),
        ),
    ]
